# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 599ee753634904821b061b7a944cff500b134fd6ffff9ee43dd80c118e8e62caf5f3546457bbafaa968e135234092f2f03ee4278a66db5193bc2bf207a458907

test:
  secret_key_base: c66f8aa6f89da0cff0a8838cd88cc6378211ceb851568b242cd3de5419e7862767d01cac7de2f1625bf239765ff8f2f4d84f41b06a6cd56b0fa21c6be0769438

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
